# Settings

CASSANDRA_IP = "127.0.0.1"
CASSANDRA_PORT = 9042
CASSANDRA_KEY_SPACE = None
CASSANDRA_TABLE_NAME = None

INITIAL_TRAINING_POINTS = 1500
PREDICTION_STEPS_IN_SECONDS = 12

TIME_COLUMN = None

MODEL_LOCATION = "models/"
MODEL_ARCHIVE = "archive/"
